-- MySQL Script generated by MySQL Workbench
-- 05/29/19 23:19:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS `stock_market` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `stock_market` ;



CREATE TABLE IF NOT EXISTS `stock_market`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(50) NOT NULL,
  `us_password` VARCHAR(100) NOT NULL,
  `us_user_type` VARCHAR(8) NOT NULL,
  `us_email` VARCHAR(50) UNIQUE NOT NULL,
  `us_mobile_number` BIGINT(10) UNIQUE NOT NULL,
  `us_status` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `stock_market`.`sector` (
  `se_id` INT(11) NOT NULL AUTO_INCREMENT,
  `se_name` VARCHAR(30) NULL DEFAULT NULL,
  `se_brief` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`se_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_market`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock_market`.`company` (
  `co_id` INT(11) NOT NULL AUTO_INCREMENT,
  `co_name` VARCHAR(50) NULL DEFAULT NULL,
  `co_turnover` BIGINT(20) NULL DEFAULT NULL,
  `co_ceo` VARCHAR(20) NULL DEFAULT NULL,
  `co_board_of_directors` VARCHAR(100) NULL DEFAULT NULL,
  `co_stock_exchange` TINYINT(1) NULL DEFAULT NULL,
  `co_sector` VARCHAR(50) NULL DEFAULT NULL,
  `co_breif_writeup` VARCHAR(100) NULL DEFAULT NULL,
  `co_stock_code` INT(11) NULL DEFAULT NULL,
  `co_se_id` INT(11) NOT NULL,
  PRIMARY KEY (`co_id`, `co_se_id`),
  INDEX `fk_company_sector1_idx` (`co_se_id` ASC),
  CONSTRAINT `fk_company_sector1`
    FOREIGN KEY (`co_se_id`)
    REFERENCES `stock_market`.`sector` (`se_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

select * from company;
-- -----------------------------------------------------
-- Table `stock_market`.`stock_exchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock_market`.`stock_exchange` (
  `st_id` INT(11) NOT NULL AUTO_INCREMENT,
  `st_stock_exchange` VARCHAR(10) NULL DEFAULT NULL,
  `st_brief` VARCHAR(100) NULL DEFAULT NULL,
  `st_contact_address` VARCHAR(100) NULL DEFAULT NULL,
  `st_remarks` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`st_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `stock_market`.`stock_price` (
  `sp_id` INT NOT NULL AUTO_INCREMENT,
  `sp_company_code` INT(11),
  `sp_stock_exchange` VARCHAR(10),
  `sp_current_price` BIGINT,
  `sp_date` Date,
  `sp_time` TIME,
  PRIMARY KEY (`sp_id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `stock_market`.`ipo_details` (
  `ip_id` INT NOT NULL AUTO_INCREMENT,
  `ip_company_name` VARCHAR(30),
  `ip_stock_exchange` VARCHAR(10),
  `ip_price_per_share` BIGINT,
  `ip_total_shares` INT,
  `ip_open_date_time` DATETIME,
   `ip_remarks` VARCHAR(100),
  PRIMARY KEY (`ip_id`))
ENGINE = InnoDB;


select * from user;
